export const FILTER_CHANGED = 'FILTER_CHANGED';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SEARCH_TERM = 'SEARCH_TERM';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
